=== msd1kpei/OR11-eCLEARSCollateral/OR11-eCLEARSCollateral/xsd/Query_COLLEQUITY.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Query_COLLEQUITY" xmlns="http://xmlns.oracle.com/pcbpel/adapter/db/Query_COLLEQUITY" elementFormDefault="qualified" attributeFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="Query_COLLEQUITYInput" type="Query_COLLEQUITYInput"/>
   <xs:complexType name="Query_COLLEQUITYInput">
      <xs:sequence>
         <xs:element name="lownum" type="xs:decimal" nillable="true"/>
         <xs:element name="hinum" type="xs:decimal" nillable="true"/>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="Query_COLLEQUITYOutputCollection" type="Query_COLLEQUITYOutputCollection"/>
   <xs:complexType name="Query_COLLEQUITYOutputCollection">
      <xs:sequence>
         <xs:element name="Query_COLLEQUITYOutput" type="Query_COLLEQUITYOutput" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Query_COLLEQUITYOutput">
      <xs:sequence>
         <xs:element name="ROWNUM" type="xs:decimal" nillable="true"/>
         <xs:element name="HEADERID" type="xs:string" nillable="true"/>
         <xs:element name="ASAT" type="xs:string" nillable="true"/>
         <xs:element name="SOURCESYSTEM" type="xs:string" nillable="true"/>
         <xs:element name="DEALID" type="xs:string" nillable="true"/>
         <xs:element name="DEALTYPE" type="xs:string" nillable="true"/>
         <xs:element name="DEALDATE" type="xs:string" nillable="true"/>
         <xs:element name="DSTATUS" type="xs:string" nillable="true"/>
         <xs:element name="TRADEID" type="xs:string" nillable="true"/>
         <xs:element name="TRADEDATE" type="xs:string" nillable="true"/>
         <xs:element name="TRADETYPE" type="xs:string" nillable="true"/>
         <xs:element name="COUNTERPARTY" type="xs:string" nillable="true"/>
         <xs:element name="INTERNALUNIT" type="xs:string" nillable="true"/>
         <xs:element name="BUYSELL" type="xs:string" nillable="true"/>
         <xs:element name="TSTATUS" type="xs:string" nillable="true"/>
         <xs:element name="INSTRUMENTID" type="xs:string" nillable="true"/>
         <xs:element name="NUMBERSHARES" type="xs:decimal" nillable="true"/>
         <xs:element name="EXCHANGECODE" type="xs:string" nillable="true"/>
         <xs:element name="CURRENCY" type="xs:string" nillable="true"/>
         <xs:element name="PAYMENTTYPE" type="xs:string" nillable="true"/>
         <xs:element name="PAYCURRENCY" type="xs:string" nillable="true"/>
         <xs:element name="PAYAMOUNT" type="xs:decimal" nillable="true"/>
         <xs:element name="PAYMENTDATE" type="xs:string" nillable="true"/>
         <xs:element name="EXTACC" type="xs:string" nillable="true"/>
         <xs:element name="EXTACCVAL" type="xs:string" nillable="true"/>
         <xs:element name="EXTMRKT" type="xs:string" nillable="true"/>
         <xs:element name="VALMRKT" type="xs:string" nillable="true"/>
      </xs:sequence>
   </xs:complexType>
</xs:schema>

=== msd1kpei/OR11-eCLEARSCollateral/OR11-eCLEARSCollateral/public_html/merge_collEquity-Source-collEquity_Query_COLLEQUITY_OutputVariable.Query_COLLEQUITYOutputCollection.xml
<?xml version='1.0' encoding='UTF-8'?>
<Query_COLLEQUITYOutputCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.oracle.com/pcbpel/adapter/db/Query_COLLEQUITY file:/C:/WORK/DEVELOPMENT/ARIS-KPEI-PROJECT/OR11-eCLEARSCollateral/xsd/Query_COLLEQUITY.xsd" xmlns="http://xmlns.oracle.com/pcbpel/adapter/db/Query_COLLEQUITY">
   <Query_COLLEQUITYOutput>
      <ROWNUM>82</ROWNUM>
      <HEADERID>HEADERID83</HEADERID>
      <ASAT>ASAT84</ASAT>
      <SOURCESYSTEM>SOURCESYSTEM85</SOURCESYSTEM>
      <DEALID>DEALID86</DEALID>
      <DEALTYPE>DEALTYPE87</DEALTYPE>
      <DEALDATE>DEALDATE88</DEALDATE>
      <DSTATUS>DSTATUS89</DSTATUS>
      <TRADEID>TRADEID90</TRADEID>
      <TRADEDATE>TRADEDATE91</TRADEDATE>
      <TRADETYPE>TRADETYPE92</TRADETYPE>
      <COUNTERPARTY>COUNTERPARTY93</COUNTERPARTY>
      <INTERNALUNIT>INTERNALUNIT94</INTERNALUNIT>
      <BUYSELL>BUYSELL95</BUYSELL>
      <TSTATUS>TSTATUS96</TSTATUS>
      <INSTRUMENTID>INSTRUMENTID97</INSTRUMENTID>
      <NUMBERSHARES>98</NUMBERSHARES>
      <EXCHANGECODE>EXCHANGECODE99</EXCHANGECODE>
      <CURRENCY>CURRENCY100</CURRENCY>
      <PAYMENTTYPE>PAYMENTTYPE101</PAYMENTTYPE>
      <PAYCURRENCY>PAYCURRENCY102</PAYCURRENCY>
      <PAYAMOUNT>103</PAYAMOUNT>
      <PAYMENTDATE>PAYMENTDATE104</PAYMENTDATE>
      <EXTACC>EXTACC105</EXTACC>
      <EXTACCVAL>EXTACCVAL106</EXTACCVAL>
      <EXTMRKT>EXTMRKT107</EXTMRKT>
      <VALMRKT>VALMRKT108</VALMRKT>
   </Query_COLLEQUITYOutput>
   <Query_COLLEQUITYOutput>
      <ROWNUM>109</ROWNUM>
      <HEADERID>HEADERID110</HEADERID>
      <ASAT>ASAT111</ASAT>
      <SOURCESYSTEM>SOURCESYSTEM112</SOURCESYSTEM>
      <DEALID>DEALID113</DEALID>
      <DEALTYPE>DEALTYPE114</DEALTYPE>
      <DEALDATE>DEALDATE115</DEALDATE>
      <DSTATUS>DSTATUS116</DSTATUS>
      <TRADEID>TRADEID117</TRADEID>
      <TRADEDATE>TRADEDATE118</TRADEDATE>
      <TRADETYPE>TRADETYPE119</TRADETYPE>
      <COUNTERPARTY>COUNTERPARTY120</COUNTERPARTY>
      <INTERNALUNIT>INTERNALUNIT121</INTERNALUNIT>
      <BUYSELL>BUYSELL122</BUYSELL>
      <TSTATUS>TSTATUS123</TSTATUS>
      <INSTRUMENTID>INSTRUMENTID124</INSTRUMENTID>
      <NUMBERSHARES>125</NUMBERSHARES>
      <EXCHANGECODE>EXCHANGECODE126</EXCHANGECODE>
      <CURRENCY>CURRENCY127</CURRENCY>
      <PAYMENTTYPE>PAYMENTTYPE128</PAYMENTTYPE>
      <PAYCURRENCY>PAYCURRENCY129</PAYCURRENCY>
      <PAYAMOUNT>130</PAYAMOUNT>
      <PAYMENTDATE>PAYMENTDATE131</PAYMENTDATE>
      <EXTACC>EXTACC132</EXTACC>
      <EXTACCVAL>EXTACCVAL133</EXTACCVAL>
      <EXTMRKT>EXTMRKT134</EXTMRKT>
      <VALMRKT>VALMRKT135</VALMRKT>
   </Query_COLLEQUITYOutput>
   <Query_COLLEQUITYOutput>
      <ROWNUM>136</ROWNUM>
      <HEADERID>HEADERID137</HEADERID>
      <ASAT>ASAT138</ASAT>
      <SOURCESYSTEM>SOURCESYSTEM139</SOURCESYSTEM>
      <DEALID>DEALID140</DEALID>
      <DEALTYPE>DEALTYPE141</DEALTYPE>
      <DEALDATE>DEALDATE142</DEALDATE>
      <DSTATUS>DSTATUS143</DSTATUS>
      <TRADEID>TRADEID144</TRADEID>
      <TRADEDATE>TRADEDATE145</TRADEDATE>
      <TRADETYPE>TRADETYPE146</TRADETYPE>
      <COUNTERPARTY>COUNTERPARTY147</COUNTERPARTY>
      <INTERNALUNIT>INTERNALUNIT148</INTERNALUNIT>
      <BUYSELL>BUYSELL149</BUYSELL>
      <TSTATUS>TSTATUS150</TSTATUS>
      <INSTRUMENTID>INSTRUMENTID151</INSTRUMENTID>
      <NUMBERSHARES>152</NUMBERSHARES>
      <EXCHANGECODE>EXCHANGECODE153</EXCHANGECODE>
      <CURRENCY>CURRENCY154</CURRENCY>
      <PAYMENTTYPE>PAYMENTTYPE155</PAYMENTTYPE>
      <PAYCURRENCY>PAYCURRENCY156</PAYCURRENCY>
      <PAYAMOUNT>157</PAYAMOUNT>
      <PAYMENTDATE>PAYMENTDATE158</PAYMENTDATE>
      <EXTACC>EXTACC159</EXTACC>
      <EXTACCVAL>EXTACCVAL160</EXTACCVAL>
      <EXTMRKT>EXTMRKT161</EXTMRKT>
      <VALMRKT>VALMRKT162</VALMRKT>
   </Query_COLLEQUITYOutput>
</Query_COLLEQUITYOutputCollection>
