=== msd1kpei/OR11-eCLEARSCollateral/OR11-eCLEARSCollateral/xsd/Query_COLLCASH.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/COLLCASH" xmlns="http://xmlns.oracle.com/pcbpel/adapter/db/COLLCASH" elementFormDefault="qualified" attributeFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="COLLCASHInput" type="COLLCASHInput"/>
   <xs:complexType name="COLLCASHInput">
      <xs:sequence>
         <xs:element name="lownum" type="xs:decimal" nillable="true"/>
         <xs:element name="hinum" type="xs:decimal" nillable="true"/>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="COLLCASHOutputCollection" type="COLLCASHOutputCollection"/>
   <xs:complexType name="COLLCASHOutputCollection">
      <xs:sequence>
         <xs:element name="COLLCASHOutput" type="COLLCASHOutput" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="COLLCASHOutput">
      <xs:sequence>
         <xs:element name="ROWNUM" type="xs:decimal" nillable="true"/>
         <xs:element name="HEADERID" type="xs:string" nillable="true"/>
         <xs:element name="ASAT" type="xs:string" nillable="true"/>
         <xs:element name="SOURCESYSTEM" type="xs:string" nillable="true"/>
         <xs:element name="DEALID" type="xs:string" nillable="true"/>
         <xs:element name="DEALTYPE" type="xs:string" nillable="true"/>
         <xs:element name="DEALDATE" type="xs:string" nillable="true"/>
         <xs:element name="DSTATUS" type="xs:string" nillable="true"/>
         <xs:element name="TRADEID" type="xs:string" nillable="true"/>
         <xs:element name="TRADEDATE" type="xs:string" nillable="true"/>
         <xs:element name="TRADETYPE" type="xs:string" nillable="true"/>
         <xs:element name="COUNTERPARTY" type="xs:string" nillable="true"/>
         <xs:element name="INTERNALUNIT" type="xs:string" nillable="true"/>
         <xs:element name="BUYSELL" type="xs:string" nillable="true"/>
         <xs:element name="TSTATUS" type="xs:string" nillable="true"/>
         <xs:element name="INSTRUMENTID" type="xs:string" nillable="true"/>
         <xs:element name="NUMBERSHARES" type="xs:decimal" nillable="true"/>
         <xs:element name="EXCHANGECODE" type="xs:string" nillable="true"/>
         <xs:element name="CURRENCY" type="xs:string" nillable="true"/>
         <xs:element name="PAYMENTTYPE" type="xs:string" nillable="true"/>
         <xs:element name="PAYCURRENCY" type="xs:string" nillable="true"/>
         <xs:element name="PAYAMOUNT" type="xs:decimal" nillable="true"/>
         <xs:element name="PAYMENTDATE" type="xs:string" nillable="true"/>
         <xs:element name="EXTACC" type="xs:string" nillable="true"/>
         <xs:element name="EXTACCVAL" type="xs:string" nillable="true"/>
         <xs:element name="EXTMRKT" type="xs:string" nillable="true"/>
         <xs:element name="VALMRKT" type="xs:string" nillable="true"/>
      </xs:sequence>
   </xs:complexType>
</xs:schema>

=== msd1kpei/OR11-eCLEARSCollateral/OR11-eCLEARSCollateral/public_html/merge_collCash-Source-Query_lownum_hinum_Query_COLLCASH_OutputVariable.COLLCASHOutputCollection.xml
<?xml version='1.0' encoding='UTF-8'?>
<COLLCASHOutputCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.oracle.com/pcbpel/adapter/db/COLLCASH file:/C:/WORK/DEVELOPMENT/ARIS-KPEI-PROJECT/OR11-eCLEARSCollateral/xsd/Query_COLLCASH.xsd" xmlns="http://xmlns.oracle.com/pcbpel/adapter/db/COLLCASH">
   <COLLCASHOutput>
      <ROWNUM>9999999</ROWNUM>
      <HEADERID>HEADERID164</HEADERID>
      <ASAT>ASAT165</ASAT>
      <SOURCESYSTEM>SOURCESYSTEM166</SOURCESYSTEM>
      <DEALID>DEALID167</DEALID>
      <DEALTYPE>DEALTYPE168</DEALTYPE>
      <DEALDATE>DEALDATE169</DEALDATE>
      <DSTATUS>DSTATUS170</DSTATUS>
      <TRADEID>TRADEID171</TRADEID>
      <TRADEDATE>TRADEDATE172</TRADEDATE>
      <TRADETYPE>TRADETYPE173</TRADETYPE>
      <COUNTERPARTY>COUNTERPARTY174</COUNTERPARTY>
      <INTERNALUNIT>INTERNALUNIT175</INTERNALUNIT>
      <BUYSELL>BUYSELL176</BUYSELL>
      <TSTATUS>TSTATUS177</TSTATUS>
      <INSTRUMENTID>INSTRUMENTID178</INSTRUMENTID>
      <NUMBERSHARES>179</NUMBERSHARES>
      <EXCHANGECODE>EXCHANGECODE180</EXCHANGECODE>
      <CURRENCY>CURRENCY181</CURRENCY>
      <PAYMENTTYPE>PAYMENTTYPE182</PAYMENTTYPE>
      <PAYCURRENCY>PAYCURRENCY183</PAYCURRENCY>
      <PAYAMOUNT>184</PAYAMOUNT>
      <PAYMENTDATE>PAYMENTDATE185</PAYMENTDATE>
      <EXTACC>EXTACC186</EXTACC>
      <EXTACCVAL>EXTACCVAL187</EXTACCVAL>
      <EXTMRKT>EXTMRKT188</EXTMRKT>
      <VALMRKT>VALMRKT189</VALMRKT>
   </COLLCASHOutput>
   <COLLCASHOutput>
      <ROWNUM>99999991</ROWNUM>
      <HEADERID>HEADERID191</HEADERID>
      <ASAT>ASAT192</ASAT>
      <SOURCESYSTEM>SOURCESYSTEM193</SOURCESYSTEM>
      <DEALID>DEALID194</DEALID>
      <DEALTYPE>DEALTYPE195</DEALTYPE>
      <DEALDATE>DEALDATE196</DEALDATE>
      <DSTATUS>DSTATUS197</DSTATUS>
      <TRADEID>TRADEID198</TRADEID>
      <TRADEDATE>TRADEDATE199</TRADEDATE>
      <TRADETYPE>TRADETYPE200</TRADETYPE>
      <COUNTERPARTY>COUNTERPARTY201</COUNTERPARTY>
      <INTERNALUNIT>INTERNALUNIT202</INTERNALUNIT>
      <BUYSELL>BUYSELL203</BUYSELL>
      <TSTATUS>TSTATUS204</TSTATUS>
      <INSTRUMENTID>INSTRUMENTID205</INSTRUMENTID>
      <NUMBERSHARES>206</NUMBERSHARES>
      <EXCHANGECODE>EXCHANGECODE207</EXCHANGECODE>
      <CURRENCY>CURRENCY208</CURRENCY>
      <PAYMENTTYPE>PAYMENTTYPE209</PAYMENTTYPE>
      <PAYCURRENCY>PAYCURRENCY210</PAYCURRENCY>
      <PAYAMOUNT>211</PAYAMOUNT>
      <PAYMENTDATE>PAYMENTDATE212</PAYMENTDATE>
      <EXTACC>EXTACC213</EXTACC>
      <EXTACCVAL>EXTACCVAL214</EXTACCVAL>
      <EXTMRKT>EXTMRKT215</EXTMRKT>
      <VALMRKT>VALMRKT216</VALMRKT>
   </COLLCASHOutput>
   <COLLCASHOutput>
      <ROWNUM>217</ROWNUM>
      <HEADERID>HEADERID218</HEADERID>
      <ASAT>ASAT219</ASAT>
      <SOURCESYSTEM>SOURCESYSTEM220</SOURCESYSTEM>
      <DEALID>DEALID221</DEALID>
      <DEALTYPE>DEALTYPE222</DEALTYPE>
      <DEALDATE>DEALDATE223</DEALDATE>
      <DSTATUS>DSTATUS224</DSTATUS>
      <TRADEID>TRADEID225</TRADEID>
      <TRADEDATE>TRADEDATE226</TRADEDATE>
      <TRADETYPE>TRADETYPE227</TRADETYPE>
      <COUNTERPARTY>COUNTERPARTY228</COUNTERPARTY>
      <INTERNALUNIT>INTERNALUNIT229</INTERNALUNIT>
      <BUYSELL>BUYSELL230</BUYSELL>
      <TSTATUS>TSTATUS231</TSTATUS>
      <INSTRUMENTID>INSTRUMENTID232</INSTRUMENTID>
      <NUMBERSHARES>233</NUMBERSHARES>
      <EXCHANGECODE>EXCHANGECODE234</EXCHANGECODE>
      <CURRENCY>CURRENCY235</CURRENCY>
      <PAYMENTTYPE>PAYMENTTYPE236</PAYMENTTYPE>
      <PAYCURRENCY>PAYCURRENCY237</PAYCURRENCY>
      <PAYAMOUNT>238</PAYAMOUNT>
      <PAYMENTDATE>PAYMENTDATE239</PAYMENTDATE>
      <EXTACC>EXTACC240</EXTACC>
      <EXTACCVAL>EXTACCVAL241</EXTACCVAL>
      <EXTMRKT>EXTMRKT242</EXTMRKT>
      <VALMRKT>VALMRKT243</VALMRKT>
   </COLLCASHOutput>
</COLLCASHOutputCollection>
